---
#- name: Update all packages to their latest version
  #ansible.builtin.apt:
    # name: "*"
      #state: latest

- name: Setup Fluent Bit repo
  include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Install Fluent Bit
  include_tasks: install.yml

- name: Configure Fluent Bit
  include_tasks: config.yml

- name: Enable and Start Fluent Bit
  service:
    name: td-agent-bit
    enabled: true
    state: started
